// Code generated by "stringer -type=handType"; DO NOT EDIT.

package day07

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[highCard-0]
	_ = x[onePair-1]
	_ = x[twoPair-2]
	_ = x[threeOfAKind-3]
	_ = x[fullHouse-4]
	_ = x[fourOfAKind-5]
	_ = x[fiveOfAKind-6]
}

const _handType_name = "highCardonePairtwoPairthreeOfAKindfullHousefourOfAKindfiveOfAKind"

var _handType_index = [...]uint8{0, 8, 15, 22, 34, 43, 54, 65}

func (i handType) String() string {
	if i < 0 || i >= handType(len(_handType_index)-1) {
		return "handType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _handType_name[_handType_index[i]:_handType_index[i+1]]
}
