// Code generated by "stringer -type=condition"; DO NOT EDIT.

package day12

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[operational-0]
	_ = x[damaged-1]
	_ = x[unknown-2]
}

const _condition_name = "operationaldamagedunknown"

var _condition_index = [...]uint8{0, 11, 18, 25}

func (i condition) String() string {
	if i < 0 || i >= condition(len(_condition_index)-1) {
		return "condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _condition_name[_condition_index[i]:_condition_index[i+1]]
}
