#!/usr/bin/env python

import sys
from bs4 import BeautifulSoup
import requests


def get_sample_input(day) -> str:
    url = f"https://adventofcode.com/2023/day/{day}"
    html = requests.get(url).text
    soup = BeautifulSoup(html, "html.parser")
    pre = soup.find("pre")
    assert pre is not None, "No sample input found"
    return pre.text


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: get_sample_input.py <day>")
        sys.exit(1)
    day = sys.argv[1]
    try:
        day = int(day)
    except ValueError:
        print("Invalid day")
        sys.exit(1)

    if day < 1 or day > 25:
        print("Invalid day")
        sys.exit(1)

    url = f"https://adventofcode.com/2023/day/{day}"

    html = requests.get(url).text

    sample_input = get_sample_input(day)

    path = f"embeds/inputs/day{day:02}/sample-input.txt"

    print(f"Writing sample input for day {day} to {path}")

    with open(path, "w") as f:
        f.write(sample_input)
