#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 <day_num>"
    exit 1
fi

# check if input is a number
if [ "$1" -eq "$1" ] 2>/dev/null
then
    echo "Day number is a number"
else
    echo "Day number should be a number"
    exit 1
fi

# check if input is between 1 and 25
if [ "$1" -lt 1 ] || [ "$1" -gt 25 ]
then
    echo "Day number should be between 1 and 25"
    exit 1
fi

dayDir=$(printf "day%02d" "$1")
dayTestFile=$(printf "%s/%s_test.go" "$dayDir" "$dayDir")

cat template_test.go.template | sed "s/template/$dayDir/g" > "$dayTestFile"

cat solutions/solutions.go | sed "/\/\/.*$dayDir/s/^[[:space:]]*\/\/[[:space:]]*//g" > solutions/solutions.go.tmp
mv solutions/solutions.go.tmp solutions/solutions.go

cat solutions/solutions.go | sed "/^[[:space:]]*ValidEnd/s/=[[:space:]]*[0-9]*/= $1/" > solutions/solutions.go.tmp
mv solutions/solutions.go.tmp solutions/solutions.go

gofmt -w solutions/solutions.go

echo "Template created at  $dayTestFile"
echo "Solutions file updated"
